Update package metadata for setuptools v78 (#28)
Recently, some build processes have started to balk at building this
from source. They give an error like:

    setuptools.errors.InvalidConfigError: Invalid dash-separated key
    'description-file' in 'metadata' (setup.cfg), please use the
    underscore name 'description_file' instead.

It seems like we need to be compatible with this change in
setuptools v78:

> Setuptools no longer accepts options containing [...] dash
> characters in setup.cfg. Please ensure to write the options in
> setup.cfg using the lower_snake_case convention (e.g. [...]
> install-requires => install_requires).

https://setuptools.pypa.io/en/latest/history.html#deprecations-and-removals