Update package metadata for setuptools v78...
... because it seems like recently Poetry 1.8.x and 2.x have started to
balk at building this from source. They give an error like:

    setuptools.errors.InvalidConfigError: Invalid dash-separated key
    'description-file' in 'metadata' (setup.cfg), please use the
    underscore name 'description_file' instead.